[project]
name = "corporate-store-of-parks-and-squares"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "black>=25.11.0",
    "django>=5.2.8",
    "psycopg2>=2.9.11",
]
